baseURL = "https://web.yelleis.top/"
languageCode = "zh-CN"
title = "YelleğŸ¦‹ NAV"
theme = "hugo-webstack"

#true:å…è®¸å¤§å†™å­—æ¯urlè·¯å¾„ï¼Œfalse:å°†urlè·¯å¾„è½¬æ¢æˆå°å†™
disablePathToLower = true

#é¡µè„šï¼šä½œè€…åå­—
copyright = "YelleğŸ¦‹"

#ç½‘ç«™ä¿¡æ¯ï¼Œä¸æ˜¾ç¤ºï¼Œä»…ä¾›æœç´¢å¼•æ“å‚è€ƒ
[params]
  keywords = "ç½‘é¡µå¯¼èˆª,webstack,hugo"
  description = "YelleğŸ¦‹ â€” ç½‘å€å¯¼èˆª"

#æ˜¯å¦å¼€å¯æœç´¢æ ï¼Œtrueå¼€å¯ï¼Œfalseå…³é—­
[params.search]
  enable = true

#è®¾ç½®é»˜è®¤æ¨¡å¼ï¼Œtrueæš—è‰²æ¨¡å¼ï¼Œfalseäº®è‰²æ¨¡å¼
[params.darkmode]
  enable = false

#ä¸»é¡µèœå•æ æ˜¾ç¤ºåœ¨çº¿ç¼–è¾‘æŒ‰é’®ï¼ˆç¼–è¾‘githubæ–‡ä»¶ï¼Œé€‚ç”¨äºè‡ªåŠ¨åŒ–éƒ¨ç½²çš„æƒ…å†µï¼‰
[params.edit]
  # trueæ˜¾ç¤ºæŒ‰é’®ï¼Œfalseä¸æ˜¾ç¤º
  enable = false
  # ç«™ç‚¹å¯¹åº”çš„githubä»“åº“é“¾æ¥
  url = "https://github.com/oulh/nav/blob/main/data/webstack.yml"
  
#æ¡Œé¢ç«¯å³ä¸Šè§’githubæŒ‰é’®
[params.github]
  enable = false
  url = "https://github.com/oulh/nav"
  
  [permalinks]  
  404 = "/404.html"
  
#æ˜¯å¦å¯¹æœ¬åœ°æœç´¢åŠŸèƒ½å¼€å¯æ‹¼éŸ³åŒ¹é…ï¼Œtrueå¼€å¯ï¼Œfalseç¦æ­¢ã€‚
#æ‹¼éŸ³åº“ä½“ç§¯337kï¼Œæ”¯æŒé¦–å­—æ¯åŒ¹é…
[params.pinyin]
  enable = true
